AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Single-stack, multi-repo OIDC IAM Role for GitHub Actions (see docs/efficient_oidc_multi_repo.md)

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub Organization name (case-sensitive, e.g., 'YourOrg')
  AllowedRepos:
    Type: CommaDelimitedList
    Description: Comma-separated list of fully formatted GitHub repository patterns (e.g., 'repo:PaulDuvall/gha-aws-oidc-bootstrap:*,repo:PaulDuvall/gha-aws-oidc-bootstrap-2:*')
  RoleName:
    Type: String
    Default: github-oidc-multi-repo-role
    Description: Name for the IAM Role

Resources:
  GitHubOidcMultiRepoRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: 'sts.amazonaws.com'
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub 'repo:${GitHubOrg}/*'
      Path: /
      Description: "IAM Role for GitHub Actions OIDC integration supporting multiple repositories."
      ManagedPolicyArns: [] # Add managed policies as needed
      Policies: [] # Leave empty and use setup_oidc.sh to apply all inline policies from the policies/ directory after stack deployment

Outputs:
  RoleArn:
    Description: ARN of the OIDC IAM Role
    Value: !GetAtt GitHubOidcMultiRepoRole.Arn
